apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: production
spec:
  encryptedData:
    image-creds.yaml: AgB7n61pg2cpH2I/9ou8D4KwbW9+TVxvmHeUpp4rY4DMGecGODRAtEqNCRx/9cRAFBB8ky50/GlfQWWZ5U/vols0u0w/FWcVYH9UPb5VuXAgyb9S4HJgXsKsssahJ0MtByncvlXL/11vfho0AppIXSCy7gfOIRahHmwh1JbmvP1kKW6CZHhUi2XrPhWwS1whDGHhcDdhswqLy3QSybMSkxvWe+8U9RIrF0PCNJpGda5Q0+Tp6hNe3f32tfY/P3c74DxS0I8aEHrWZI2ifogI8qHqPC8acxviKUJeMbdmTRTccMy09MJo2z5kfty7/AsdfdHPjQ+nsDLelBBg6CKsEhXhVHiB0LK/hxhy8MIyiVkKrkpa6Tzlr4aOWz2UA77YAyK1olmRHjzeGV9zQzcz7h5nODN+m8x8Gj6tjolGW8IlrehQ7A5mQYs5W1t902wNBH8UmOlGw1cmCrmVm2hk4ALCrP+EneSWnSuET3TgxAMGusIMe+YuPhu3jv63hg4HYYriVSYFsHto4j2YY/8ZRYj3cJNrEVrHZbeloHlbI16Mn/+JdpB/1BYcOLLZXXp/GttLF9coXVl7NFkOWsrNEdoVBSje9xQ6zMuR/qFgZydtljZ+u+zmg5t6XhKllhidJcJOX9hGW2fntZ5EMa1jm3VdjHUGPq8gK5Myl9oFlv5KiyTR6+PZHimzzMsZYMQgeDdcx7uT+ettH6o4PP0WXpHA1AC8UkP3CWejjz9esASeZwrbXDRS900+hKWhktJGwaum8w5TXp3iUUmPWuwZI2o+SMI=
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: production
status: {}

