apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: production
spec:
  encryptedData:
    image-creds.yaml: AgAgQyw6lRGA6YviwBaMw7fA68IIoSpMvjArLX8saB3VD8i1ckCj8wlHK2m2MPcknpIFi0zQn/xOQZ+AeGiJYQKsDvrrMUnQLFtKKtRCRJVGbDHuDjNKfdgeNBgw/mV8aw7pZnBJZ4laEsUTt47klqtjC+/psNGO1RPDeTSsZLZtSwi6Ew3f2sqO6f7dz6unT8vX1YY3+BN96oCuyBgjAZDUCaai8uaAVGjxiAlUF2VDx/pv4QzlNYb90TYLa6ugR62fm0eBdTyy4xPAlaAYRwjhN3pM2MQH62asz1x+xOqQMHrRXnVU2cgZ8FBnDDlGOuFaBFLIxnZzPAn4xhQPBa4fE6dLxRoW0wiLxdn41DMPy+Jv++UhusYN+5+/yqNeLSJV3Rnp7bdMnMrajzrIOsgeTgCX9d2eZS9sD1VgY40SPMvjV0Y8hUGyM1NIshd+IH9GjZX0w7o/c9gORHys+I7y6iNE03afaonwqK9bWS5KgoGnIkoy5dRQB2guwXUO9PSR+9G/2LNVqwbrf1xcuAfmhuQQytWoORBwfrqMBgEzVWK0sS0FP28DWWkxVon3+Sx28rYWx8YbEH0tEDkpLvnTzLVhXScNodDm+t8jt/9TCeCHRByFgLUU3FryIKbyx2w9ilHQVRAEeLk6CruMDXDNb18n1DroW+rr4NvGRYFY6tOglZknDeb00yAIwH2g7WVupK7BaTB8Slk2uNX7r4NzJ8sWVf0fz3fXe2WEiszV5U6eqetLVTd/UYzG
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: production
status: {}

