apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: production
spec:
  encryptedData:
    image-creds.yaml: AgAuBbzURo12o+SDEf7IzyBforCaT+IetWY46MVkl7gvCoVrLCBl2k9oC4liXkMMQCxjNg8ZmL1xZ7pnI5L6zJ3YjU9A6DDgRGE8OoO0zjzGGAlTaxq5RvR/2t1QwuEqStKdwWhlrArMJv1ezcdpQ4Goc1t7usO91JyCdhLQrxERhHzI32OtkP4aoVNk0XlemQNMtdpMvIKvCQBJ0XniMrE79zRLSAHnP5gIP/VCpIz9DHikfNbys1rIhSPAh6gmykjwFqjBhLnd4gcolg9O6QAVEYX/34jbJsapIJCJyCpri8crePZNTSoxO34zaDXKxuEBUZ5x5s2oioy/k034SUgXk5AWLnk4aqkcLRkmFEStpAAnRDFYBAbDG8ByGvZfaXUY7ho3XgsoQv6W1Hv06+qqK4I2H12CjolfkmJd6IDysn1wvL3MGkF04VkPjtvC0uBZrncwOMSbEif9jCUWx33CebJVyX3i3AIZ5bH+bnBIzn0AZijY034Gmh7ux9PxmItoaIFeCjJp/Wn23zi2ki/midSi12Nipp6uqEwvksCkLstbZEk4D4ohFpzZKsOo9PB+Xde1MIOP3d2/wsxdJknlSNJXB4c+IdEU9H/zXbirlQgQsps6QTwm9hTNCSREuvwGl3Ge6KXaIH0TrKHi9OC6GkVvqSQuUBRETxqOXYaFSVxAXKerdaBt1d3XApGkbNLBb1iujjtCi2lIlRuEdQ7qni0oqTZK7vt/dLm4cf6CYHvMJBO+0IpnDcoC
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: production
status: {}

