---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gateway-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: gateway-dev
  forceUpgrade: true
  chart:
    git: git@github.com:gazza7205/gateway-helm-charts
    path: charts/gateway
    ref: master
  valuesFrom:
  - secretKeyRef:
      name: image-creds
      key: image-creds.yaml
  - secretKeyRef:
      name: gateway-license
      key: license.yaml
  - secretKeyRef:
      name: env
      key: env.yaml
  values:
    replicaCount: 1
    container:
      image: docker.brcmlabs.com/gateway-dev
      tag: '1'
    imageCredentials:
      name: "docker-registry"
      registry: "docker.brcmlabs.com"
      username: "gv666792"
    hazelcast:
      enabled: true
    service:
      type: NodePort
      ports:
      - name: http
        internal: 8080
        external: 80
      - name: https
        internal: 8443
        external: 443
