apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgBEicrFDTCaSCN0IHyrTguWrzvXxxYKjbjo9xxJRIg4eQRKywTfnnXDlExUqg6SU7BdjvfQbp5GW0eyclCQOchgWAedJl6mKwb9ZlDPwRxs6XBwo77TGUHEvGU0wUmzUryQ4NVIKBDPx0J/CH5GX4ER2v/Ef1kYjDXD62VjVxsmAOX6LY+uRA9yxnIENngZn47xmWeEQKL9QtLUpRzW1o6Drd+D+D4iVkFVCzsm++B9XPlfG5n/xuoWCWj8PS9AvWR8uyfVS7tyBmutU7TBZ/PdBRbW1myJW+aCSRA0hooJ3eWoIwPKaRFwTDSXe09f/cK7JVOSpU+zuN6Bn3RV5i/1o5DOWECKEAEr7S23cTvkIM/zOTebjzsbAttFijhTdj8mvYzVqrvm9Zi5P+xkVNMjLiOquVuBUNPmhpqasWYYVns5uTciUNJJC+vTmwTzkSktsHniIloyxq42P/38cpLzrR2W3kVvUKUyfkiMqdS67zYc7ChXjkJ0oZ0PN6rejC0fOf3yhNkT59i82zJD17ePHsPbTD1ZqYivJTePSNLI3B/IgjhD0o8W96j9Jp3TF+qJr6iaVscZQTxu9u8ZViwkcGI6Wg2MbRQ0z7T4HlqMCsB3Rp5Gen5vFSfDqCNJatQHvRC9aqdNKmENnvZiXn5Qr9ajTrgyiQklL4n/ZJyISa2r15XZPRCITzHMVbTGfPbcUGHcB3m4A+AiyIsnJu5IxDX7x6/KuGWLPCy+f7/KvB8XrF7xB30KDmjf
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

