apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgBDo5daDGlyVO6VxgO1y+S0lWvdqrcGcAC6FkS/A8AZdCeHISaaYJY9gAcSz00E6xI2PTBTeNvO0XvSIzEGJYho22c+5qyaeqwxe3pgQjBjrNz5nJ5nSbt7hJIZnuxkgRPlTujSbt9So5ScwqwYnw7DcKFOhzlecW+rIpIv7Vjp7CMA04g6Ckf5w2+yjUZ+t1C1XAEI+HvexKnupz0s+jYMTR2heYhbH+uCguVi7oX1MwjwlDeE6bhuNe0BF6Sn4nUX/lr11TdT2ieZC0D0312zvViis7OwqEFWlvvhyEoiwJhm+jOiejV57nE+dobvTZoQ2cNtTFpEDVdW3NeTaDFteGsJcAxeHfJRYvW2cC2NlVP84n2dpIwKykZ4Iq1KuUTUjJiiVAMu1KRJyv3tPc4mgJXfm1lCy552MUNvsUZPCt7UyPKMEAo7PYmmNM3GdLuyaUcBHQ3jMZJVHS3sDC4xCC+nfe14wKQ+81rBqit9pFsAmTh91CGJ9Kj56G4e7pwTEeQWwh4PCrYWSoyKkeVJ6CGjn46aoNJMgawjqdTu5OnBdjyNc/H2pOp1SSNXq9NkaarEaOIXXwFRDH8kvM+C19JI1HuMadknspzEjwhah3pn2j1m6vkckrPXznsA72O0scHmb1OGcePwGqSlsI8kES893TC4Nf1AOLIIqbybJxpE1De5hBsWJAYAMWPZxPFGHpXSB6h/LlMoTmJ75Vinlm8WDjHC4Zem9zthPGTGvUi9sLYW5goC1N8E
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

