apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgAPfPsi8Q52Xh234JDAVAf0cB10rej8WZLSO+b6iwCuCXJRTiKbtjDdSJaCPblcIbaz+1AX1C3OWohHcGaSH46AwP/7MO8Fw0ElOadMjs+521drpuBpbAdFkBZk27cpZ+jiFyL1qsPjj1oRsspli7M/6843WVfsPGYRJhq8gqzBH5sORXsUCq0Y89yfr51Qn1Vx0bg8z1w0hPXzV4jTccyw7R1SMhsuDY+BdJ8Uy3xbIpUzyNnXA16HzAB0Mc+4quVcQXbPqAFU1WupYyI6a9LK1qqgLo0xZMeo/rAjj2l5Lvl9d4PKN5G66t3Jm2/5NIbzJjD1iwYLDwQbpbf56s4B2oaqrT3I3RZZ7//8vjx3dVHgMlsX86iRi3MqV8kWoMKNYlwcVuVmuy6/rU/Mlru0WgdWFdSH2ZFS7pZfGSGugeFI6URkSe2ThoD/5bOdO26yRTqQx6W5C+6UV2TYBMOWd4C3Mgt+cZo+4mF8ksjzghi9Hq7gqSTPQFCIYd8xmJRJOwIBE2d0gWP8I0S/Z7HXk/dmu3Vcq+djEskk4i0zkq2Lb/zrkjH4iKH5q+c/HPEv9T8fCq6RUNhY9caoeuUAo9AJPjEPCiQtKKmLfOR/Pbhwn/GIODoaEI7aImo6APPSO/Jd966u4ZyleDQWSXgpooN2M6alKs4X7f5vT4jSv/vMPCPLksRTZf1buOeVOMqxnlsRF2zB9Z9oCEViWJJGafAjL7xq5S5oq4LhZkvKpFgbh7dJfVX8311g
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

