apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgA/aflfAK+/7Sz1bC/BqWW5BxO4kYq4vMqCnk2yKEsw0fKyZhSelIjtmQ4QW5yAvCLv0b54HthRm0uospQUYPA7ZzyRQnObe6TCVv/0EC97W29vTGfMx7kF8rx+lNIR0tgwNgJdS7FMwvODEbTI+vgWMGOqj2iwFFZoGBF/qdcPICrpFMW+36k11GfPQKJOZJnEUji7Xx0f1lE2UifLv1VDT5wa/YuA9T1ocTHKda4LV4z0+B/lxdo+eTDO2RAaPXct3EPGKw4lJbVF13aqzX89QtFhvigaWmu4DAavmqzX0BMXo80436aqP3K1ixb0jriHh2hdy1bG/S9Luz8E2DMSsAKdpZWtYvPFKQhUtIyZxcmLQgrvnSt9UKPP/lOoqy096pclbOOa0lM6iFLBrSlUK148HplLHZVo1x/JIDyXvsM6NlWztov0qe665GhVPLaiwV5NywoIfoWStgajSmFNcPrSFi5URFCWp4vzBAxPKcEG01ljAqrPP8MogQGKuRsWDHIgS/+LzMIbHs1YdPhxYdlKsyJshGhlnxJDwQ3+mPlH5MlLdpa0bVHV3mXvFgPGwm1ijNF4RRUCIcvS5raP4pUb7fAiUslf+OuJ3996Ni2j+n0SdzuJdyNVVgx4jJ9JaukV1zdMmixwelSJdAeC6j2VzwANLF5h9y+ZgZ2CsC8Fw+2QAheWxk4N/LpYlFQspiyCk1DMNmIVeK0VVhl9WbdsIswYbZ1YTMkUrggcSJEHqUe7OUu4wZ9N
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

