apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgApXNdlm+kzwW+Wm/kdyz4VJb/gVBCbAyQOiLL4NrWHC1YHUJuvWRd5Cff4MzGUSCtACr2QtApE0mYYJg87tVVhKAwTm7PaRCYKc6DgXl5A3fx9Do87iIFiGuuY48bxSqOL8mQatGDUQ/zDvisJm5IwF3uOSE7VH85zcKKZwQSq5ksVUwco3EL3HIC566wMncquMxPkHDbwqq6vWvso5v+ZqI+DYiLgxH8oNNEvUqAEb8CC3cVGcGqr5Ue1Nvcj5jb6iDbCDb2bOqWKF2NM5F28/zWJKl3TfEXBmxzWqiPm/W08E0YmsA5XOuRDcKmQKk+rvC/wrH7T7/IAbqhGBMzU5i1PM//4Bms3zvCCf8U4JfbvvEfo2jOw9sOg6Z11ykg/j7r4qNCSYeARvpL+OD/w7hP9CJrSV2mieW1AN1x/mSVX+qj3uX9hQrBXDSNLXPYa3dwaFijTjzSUZxW1c7e5sISK1MGyC3s1Qy29l9Ro0lHhhimAgKJ9zc4jYOKotgcum1tdPYfDJRio7DWE7JSUoWtxGt876WbkpELJ+aLEt4oZ3dwTRTJ3hfcZg/27Au/XPYX2O+OXThAsDZgp6EpBb5hTC41bv2nz+BGYBG/6HYj6yeHOTxxYZPZeAmPHcGSzhj77RC2MILKRhB/Ki1hcPXtcCAaLq2245rGj9ZsOM93ii6om5xac+SFmwJoLUEeiNWZ423Ip7AQ35WeMkxHej7d66NOr0G4w17X41af0rJg9jrvYshZUhUP4
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

