apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgAhMJNJu3f75Y9pvA/2YZWIlbGMHyoSDTtwje0VY24M0bxA6X/A1xLo6DdLutmY5wdtTzLM3N31ODIhVw2PqhgrSmK2DrScC2Rtlyu79xHqujYnnWjkMMUThrdIwB1J01rbNG7ZBqPRzaOs6Mi5PK+G4S5czZnEr1ueuUKd/wPn2A3xc4fctK1NlFs3CmDpig0bpmT5/aDdSCRWRG21aHl5tYTWVekXYUx42xBn+9We7lNz5i850/BCMOe6Z7D2yIUEBG0DAdazB53MjLGzFDj6ERDwTL49uBwpsqkyuJ0f1h1LpwtmVasZTB3ALBFO1LMAllU2sQvI3oXkdoHRi3pzaHv1Mxx54l8KoN/QAJOQkld7e0ObvZ/UGU5SYrF10QNsYNc3j0cYgaIQLaao0wZB9KdhpH3cW/Q7mXtIWVpTbtl2SnmpzALEdJSq0jbax+5hNCKPaXtiZ3quDh26n43/c5DoO5mJqVbJ9gwRNWrfmNwqgTypnC9WBdFPY5J8R/51ihix7YPMykqvFvY1CotfW0LCm4psoeunpqmS0A0UPPxK1gxkH/AgvPmjoBp8+0Lkzqtptb7caKhgkCtlz0baACUJNuD3eXgUZz8TADAf3iN86jDCKwFGiQyAPX1GMeUvPN5Ka8cH5DHvemr6KY6jr5rUFucSu4zpTZkaHWwx7yV2P8DEBCeeNs95ICNc+1VuG5jswn8n84r9evNpzQcMACp1yIe2u98JUaP7BRPPOeRnkneX+BWn959t
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

