apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgB/hWcM0yGGOfSfwyCkBzB9XyHUTKbQ1MvlQK9Pt8d2aQ77US9E0nhE2VIWdj+JDDW3WYKCez+KjHSJvD5GkWjSycJy2NlYQT764A7BOr2RIdVQ1bOCxDUCa5WH82bsQzpxLM1YrGF9R9sRvOTuyr1XlV07LccRcKTiAr/DhWVmdmb28zyKhnSmhVGDL/G1X0NuJANaxudh210Ty1rmjWYu25sucChk9wttEgK0K79OT4a5e0SoPb2S91YKqheLiUJTW08sLKu2nHbHmKJtobYPalnF9JrwiQRtT2w+KKX7uw745GU9fYIPUOy10YHyZR7nUjA/hRThPtoeODO+Bo0cXbgAGQK522Rjm11k+PzkC16SSd1L8TjQdVCsrkgS3oWJtVE1xu3UDx6OGLb5nHZv5pKPDynJD+0Uwx+20DlUkLgf7zW9Ye5bdWnTRBjTU35A4K1po4TKYrq+K3iLHX3PghUjVmXEVYWIenezzE4h8GuqoHbwFkh8LXm7WeMlkINnaLJcR5ucnG8xRfrCmJPMOtddrEX+BXxzKM6qFYFi1jHMyuESyr/mms6lxhJRW5uy2i81NXduhENYhD9abmeTblSRo9wWna+kinuEJGpKDF01iyw9qny8+igECe7gEEx9MAkgdJrouKlHRk4wDgQ27+5y5XZHUE/QOLnZjTpAfZnLSX1H2AxNe6cSyHS6Y3dosF6G9ATWTZwVhxuMFTxBty8iXsfDS4pynWGmYPRP63JwZHayUo3FCw66
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

