apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgAO6nlwliz3rOW/pwvxPdiARkuFKTfRFg1uAVkWwT3Xrqmx+tPE/Uxv/ncVJLbQ7/PBfJrS4ZNOnGZTg82ESqyHtXM3EM1xx/Dw+IS5G+njI5ALQs+3qUE0PMz8u3BBw51WRSnHFApJfh5PysTpxMLQcabDKSfuzcu7PCLN7ICtfaLdfdzBlNrMae5D8CEwxiyIWVfcpLm7CbE26uwvb7aH3/G8UdcsN4Uai9Vc9bvkozsPXqyUj3ZZguiAzqq+ug40W/PwFyBGsaQXyFq/C8myhu2gnhJOw3EaRbdYsFMt5lnCM+ZsYXXXA5CPUBfrAeak3onSNnQ11gxJruI6tt5xqp8h5VoelABSMzR2ZIyrG7kiU+Il4cmqIQqzUGrgVGKy5LmdBpdIlbc5dDBCepqrOb4y0Mbjt5MI/mincAO2uGXHrzKO5bshdM4Vid8mBZDQDQ1JWqbdFfTohtrbIsBRpgAoQV5bu1n//hmOel9z0/N37mBY7rVNIzqHysgKeesLpTetkFemqcrI/+ndc/+tc4vRNXQfFwBdGa6r9C7KoIBEhiQlzCRNyLgTgDEWNwKyQvPnIlqORdtd27QrdyRhPbJWqHmby4+ARH7bKBynA4x2h91KEHgTDODZ0Ag48W6wgpdl6bpbmfpaWsBII9q80RmMXcwFjnLsv/AIaEzbnQ+Ajo00bEXcWoR2q0L4SiiUTpiLM85T1gXPxw4itpeuD0j1l8vuykzECaIiEEVt2LX/kTiixBBxur9S
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

