---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gateway-advanced
  namespace: advanced
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.container: semver:*
spec:
  releaseName: gateway-dev
  forceUpgrade: true
  chart:
    git: git@github.com:gazza7205/gateway-helm-charts
    path: charts/gateway
    ref: master
  valuesFrom:
  - secretKeyRef:
      name: image-creds
      key: image-creds.yaml
  - secretKeyRef:
      name: gateway-license
      key: license.yaml
  - secretKeyRef:
      name: env
      key: env.yaml
  values:
    replicaCount: 3
    container:
      image: docker.brcmlabs.com/repository/docker-hosted/gateway-advanced
      tag: '14'
    imageCredentials:
      name: "nexus-cicd"
      registry: "docker.brcmlabs.com"
      username: "admin"
    hazelcast:
      enabled: true
      replicaCount: 2
    service:
      ports:
      - name: http
        internal: 8080
        external: 80
      - name: https
        internal: 8443
        external: 443
